spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/auth-users
    password: root
  sql:
    init:
      platform: 'mysql'
      mode: 'always'
  jpa:
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: update
      generate-ddl: true
      properties:
        show_sql: true
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: 'true'
    locations: classpath:/db/migration
    schemas: auth-users